### ISSUE TITLE
Image uploading doesn't work

### ISSUE THREAD

**Issue by chriseickemeyerGH** [jpuri/Nib#45]
Image uploading doesn't appear to work on Windows OS in Chrome Browser, and on iOS in Safari Browser. I tried using the example from the docs website.

**Comment by jpuri** [comment]
Hey @chriseickemeyerGH , thanks for bringing this up. I am looking into it.

**Comment by chriseickemeyerGH** [comment]
Another related thing, on iOS/mobile, closing the image upload modal is impossible without refreshing the page.

**Comment by jpuri** [comment]
@chriseickemeyerGH : both these issues are fixed in version `0.4.2`.
