### ISSUE TITLE
Font select broken in demo

### ISSUE THREAD

**Issue by jEnbuska** [jpuri/Nib#47]
http://www.nibedit.com/index.html
Demos font select closes immediately after mouse up, so selecting a font a is not possible.
<img width="281" alt="Screenshot 2019-07-04 at 12 28 37" src="https://user-images.githubusercontent.com/11061511/60656083-83144d80-9e57-11e9-81e8-235b257ac229.png">

**Comment by jpuri** [comment]
Hey @jEnbuska : thanks a lot for bringing this up. A last moment change before publish broke it. Its fixed now.
